### ISSUE TITLE
A36のテストケースについて

### ISSUE THREAD

**Issue by yaneurao** [E869120/kyopro-tessoku#10]
A36の問題↓なのですが、Yesである条件として「K<=2*N-2」が必要なのですが、間違ってK<=2*Nという条件を書いている場合もACになってしまいます。
https://atcoder.jp/contests/tessoku-book/tasks/tessoku_book_aj

例)
https://atcoder.jp/contests/tessoku-book/submissions/36708676

境界条件なので、ここのテストケースは欲しいかなと思いました。

**Comment by square1001** [comment]
書籍「競技プログラミングの鉄則」をご利用いただき、誠にありがとうございます。

A36「Travel」についてですが、ご指摘の通り、K = 2N-2 になるケースが存在せず、次のようなコードでもジャッジ上では AC するようになっていました。

```python
N, K = map(int, input().split())
if K % 2 == 0 and K >= 2 * N:
	print("Yes")
else:
	print("No")
```

K = 2N-2 となるケースをいくつか追加することにより対応します。ご不便をおかけして申し訳ございませんでした。対応は数日後になる予定です。

square1001

**Comment by square1001** [comment]
対応・修正しました。

square1001
