### ISSUE TITLE
AtCoderのA37の問題文について

### ISSUE THREAD

**Issue by yaneurao** [E869120/kyopro-tessoku#11]
A37↓なのですが、「バス停」が図にないです。確認したところ、書籍の第二版で修正されているようなのですが、AtCoderの問題文も併せて修正していただけないでしょうか。

https://atcoder.jp/contests/tessoku-book/tasks/tessoku_book_ak

**Comment by square1001** [comment]
書籍「競技プログラミングの鉄則」をご利用いただき、誠にありがとうございます。

A37「Travel 2」についてですが、ご指摘の通り AtCoder 問題文中の図が更新されておらず、図の右側の「駅 1, 2, ..., M」が「バス停 1, 2, ..., M」に修正されておりませんでした。

ご不便をおかけして申し訳ございません。数日中に対応させていただきます。

square1001

**Comment by square1001** [comment]
対応・修正しました。

square1001
