### ISSUE TITLE
演習問題B52の問題文について

### ISSUE THREAD

**Issue by AyatoKinkori** [E869120/kyopro-tessoku#14]
鉄則本本文P301の下部では
`キューの先頭要素(posとする)を削除する`
となっている問題B52の箇所が

同問題のAtCoder内の問題文では
https://atcoder.jp/contests/tessoku-book/tasks/tessoku_book_dy

`キューの先頭要素を pos とする`
となっています。

おそらく誤記だと思いますので、対応の程よろしくお願いします。

**Comment by E869120** [comment]
B52 の AtCoder 上の問題文ですが，こちら側のミスでしたので修正しました．
大学の試験などの影響で返信が遅くなり申し訳ございません．

**Comment by AyatoKinkori** [comment]
お忙しいところご対応いただきありがとうございます。
試験お疲れ様でした。
