### ISSUE TITLE
A22 Sugorokuの解答例における、非連結な入力に対する処理

### ISSUE THREAD

**Issue by your-diary** [E869120/kyopro-tessoku#4]
A22 Sugorokuの解答例[`answer_A22.cpp`](https://github.com/E869120/kyopro-tessoku/blob/main/codes/cpp/chap04/answer_A22.cpp)についてです。バグ報告と質問の中間くらいのissueです。

実装されているアルゴリズムは、非連結な入力、例えば
```
n = 10
a = [10, 9, 4, 8, 10, 8, 9, 10, 10]
b = [10, 10, 4, 10, 10, 8, 10, 10, 10]
```
という入力に対して最適ではないと思います。

既にお気づきになられたため配列の初期化を
```cpp
dp[1] = 0;
for (int i = 2; i <= N; i++) dp[i] = -1000000000;
```
と修正されたのだと推測していますが、確かにこれでうまくはいくものの、非常に小さい値で初期化しているから非連結なところからの移動は`max()`の結果弾かれる(例: マス3にマス1から間接的にすら到達できなくても、マス3から配ってしまうが、`dp[3]`が極めて小さいため`max()`で弾かれる)だけで、アルゴリズム的に最適ではないように感じました。(盤面を有向グラフと見なしたときに、最初のマスから間接的にすら到達できないことを「非連結」と定義しています。グラフ理論における「非連結」ではないです。)

私は[Submission #35048873の57行目](https://atcoder.jp/contests/tessoku-book/submissions/35048873)のようにキューを用いてBFS的に連結な部分だけを移動しましたが、(キューを使うかは別としても)何らかの手段で連結判定をしたりはしないのでしょうか。(ちなみに215行目からのコードで、非連結な入力サンプルを自動生成できます。)
もしかすると競プロに慣れた方なら非連結なところから配るときに`dp[i] = -1000000000;`のような初期化をしておいて楽をするのかも知れませんが、配るdpの意味すら初めて知った身からすると、解答例を見てかなり混乱しました。

[正誤表](https://github.com/E869120/kyopro-tessoku/blob/main/errata/errata_Chap0-4.md)を見ると

> *非連結ケースの考慮漏れ*

などではなく

> *配列の初期化ミス*

と記載されているため、やはり連結判定をしないのはあくまで意図的なのかなと感じまして。

解答例をRustに移植して提出してみましたが([Submission #35049272の62行目](https://atcoder.jp/contests/tessoku-book/submissions/35049272))、私のキューによる実装よりも2倍以上速いので(91ms vs 37ms)、配るdpを実装する際、可能な限りはこういう書き方をするのが競プロ的には良いのでしょうか。

**Comment by square1001** [comment]
書籍「競技プログラミングの鉄則」およびその自動採点システムをご利用いただき、誠にありがとうございます。

#### 配る DP の初期値について

まず、第 1 版における p.138 のコードにミスがあった件について、ご不便をおかけして申し訳ございませんでした。4.7 節で扱う「貰う遷移形式」の DP で最初に「-1000000000」などの小さい値に初期化する理由は、dp[i] が「マス i まで進んだ時点で得られるスコアの最大値、ただし未到達の場合は -∞」という値になるように決めているからです。なのでもちろん、到達不可能な場合は -∞ になっています。この実装方法については、書籍 pp.135-136 にある図が参考になると思います（図では初期値を「∞ 分」に設定しています）。

補足として「非常に小さい値で初期化しているから非連結なところからの移動は max() の結果弾かれる」とコメントされていますが、例えば dp[1] = -1000000000 として dp[2] = max(dp[2], dp[1] + 150) とすると dp[2] = -999999850 と少し大きな値になります。ですので、-∞ の値はこれが N 回積み重なっても答えに影響が出ていない値に設定しています。なお、以下のような実装もできます（コード 18～21 行目に対応）。

```cpp
for (int i = 1; i <= N - 1; i++) {
	if (dp[i] != -1000000000) {
		dp[A[i]] = max(dp[A[i]], dp[i]+100);
		dp[B[i]] = max(dp[B[i]], dp[i]+150);
	}
}
```

このように書くと、到達不可能なマスのスコアがすべて「dp[i] = -1000000000」となります。

#### 「非連結な場合」における最適化について

4.7 節のコードでは非連結な場合に対して計算時間を減らすような最適化をしていませんが、どのような入力でも N に対して同様のループ回数で動作しています。以下に関してはあくまでも私の個人的な見解ですが、問題 A22 で貰う遷移形式を使った方がよいのは

1. 実装が比較的シンプルになる（p.137 の注釈 4 参照）
2. 配る遷移形式だと、各マスに対して「直前のマス」のリストを作る必要があり、この分実行時間も増える

といった感じです。そのため、BFS の要領で非連結な場合に対して最適化をしようとしても、1. と 2. 両方で良さが損なわれる（特に 2. に関しては BFS の実行時間も増える）ため、そのような最適化はしない方が良いのではないかと思いました。

square1001

**Comment by your-diary** [comment]
ご返信ありがとうございます。

確かに、
> *4.7 節のコードでは非連結な場合に対して計算時間を減らすような最適化をしていませんが、どのような入力でも N に対して同様のループ回数で動作しています。*

とのことで、私のコードは連結な場合にもキューによるオーバーヘッドが生じてしまうので、特にあらゆる入力に対する最悪ケースの実行時間が重要になる競プロにおいては、私が当初思っていたよりもメリットがないことを納得できました。非連結の可能性があるならば非連結の判定をしなければならないと思い込んでいましたが、解答例のように制約をうまく利用してよりシンプルな実装を行うことにも慣れていければと思っています。

また、貰う遷移形式を使った方が良い理由についても、大変勉強になりました。

詳細に教えていただきありがとうございます！
