### ISSUE TITLE
A28 Blackboardにおける負の整数の余りの処理

### ISSUE THREAD

**Issue by your-diary** [E869120/kyopro-tessoku#5]
例えば以下のような入力を考えます。
```
1
- 100
```
最初、黒板には`0`が書かれているため、黒板の数字は`-100`されて結果`-100`となります。これを`10000`で割ると`-100`です(†1)。

ですが、[想定解](https://github.com/E869120/kyopro-tessoku/blob/main/codes/cpp/chap05/answer_A28.cpp#L18)だと
```C++
// 引き算で答えが 0 未満になった場合
if (Answer < 0) Answer += 10000;
```
となっているので、`9900`が解となってしまいます。

今回、制約としては`A_i <= 1e+2`かつ`N <= 1e+5`なので、[Submission #35084496の55行目](https://atcoder.jp/contests/tessoku-book/submissions/35084496)のように、`1e+4`ではなく`1e+8`で割った余りを保持しておくと良いと思ったのですが、いかがでしょうか。

(†1): 定義次第です。問題文に定義が書かれていないのも混乱しましたが、C++, Java, Rust, Go, JavaScript, Julia, Swift, Bash, SQLなどの定義(*truncated*)だと`-100`です。Python, Perl, Ruby, Rなどの定義(*floored*)だと`9900`です。(参考: [*Modulo operation - Wikipedia*](https://en.wikipedia.org/wiki/Modulo_operation))

**Comment by square1001** [comment]
書籍「競技プログラミングの鉄則」およびその自動採点システムをご利用いただき、誠にありがとうございます。

本問題 (A28) の問題文がある p.165 には、制約として「黒板に書かれた数は常に 0 以上である」と書かれております。一方、AtCoder の自動採点システムでは、確認したところこのような制約は書かれておりませんでした。担当者に問い合わせましたので、近日中に修正されると思います。

なお、AtCoder の自動採点システムにおいては「黒板が書かれた数が 0 未満になるケース」は存在せず、34 ケースすべてが書籍の問題文中の制約を満たしますので、ジャッジ結果による影響はありません。そのため、書籍および GitHub 上のプログラムを変更する必要はないものと思われます。

square1001

**Comment by E869120** [comment]
対応・修正しました。
