### ISSUE TITLE
A72 Tile Paintingのテストケースは完全な貪欲法に耐性が無い

### ISSUE THREAD

**Issue by your-diary** [E869120/kyopro-tessoku#6]
[*A72 - Tile Painting*](https://atcoder.jp/contests/tessoku-book/tasks/tessoku_book_bt) についてです。

[解答例](https://github.com/E869120/kyopro-tessoku/blob/main/codes/cpp/chap10/answer_A72.cpp)は、書籍 p.417で説明があるように、行だけ全探索して列については貪欲法で解いているものと理解しています。

一方、完全な貪欲法(行と列を一緒くたに考え、最も多く白を塗れるものを採用していく)でもACしてしまいます。

一例ですが、以下のように完全な貪欲法が破綻するテストケースがあると良いと思ったのですが、いかがでしょうか。
今回の問題の場合、完全な貪欲法は実装次第で結果が変わってしまう(白く塗れる数が同じ行や列が複数あるときに、どれが選ばれるかがimplementation detailに依ってしまう)ので、あり得そうなパターンそれぞれについて示します。

## テストケース1: 列よりも行を優先的に選ぶような実装で破綻する

```
h = 5
w = 5
k = 3
c = [
    ['.', '#', '.', '.', '#']
    ['.', '#', '#', '#', '#']
    ['#', '#', '#', '#', '.']
    ['#', '#', '.', '#', '.']
    ['.', '#', '.', '#', '#']
]
```
(解答例だと`24`、完全な貪欲法だと`23`)

## テストケース2: 行よりも列を優先的に選ぶような実装で破綻する

```
h = 5
w = 5
k = 4
c = [
    ['.', '.', '#', '#', '.']
    ['.', '#', '.', '.', '#']
    ['#', '.', '.', '.', '.']
    ['.', '#', '.', '#', '#']
    ['#', '#', '#', '#', '#']
]
```
(解答例だと`25`、完全な貪欲法だと`24`)

両方ともテストケースとして組み込めば、行優先・列優先いずれの完全な貪欲法もrejectできるようになります。なお、上記のテストケースは、候補となる行(または列)が複数あったときに、どの行(または列。respectively)を選ぶかに依らず破綻してくれます。(すなわち、下記のサンプルコードでは、行番号・列番号を最小化していますが、最大化する実装や中途半端なものを選ぶ実装においても上記のテストケースでは落ちてくれます。)

---

参考: [*Submission #35315230*](https://atcoder.jp/contests/tessoku-book/submissions/35315230)
- 完全な貪欲法: 138行目
- 解答例のRust移植: 55行目
- 盤面の自動生成: 225行目

**Comment by square1001** [comment]
書籍「競技プログラミングの鉄則」およびその自動採点システムをご利用いただき、誠にありがとうございます。

A72「Tile Painting」についてですが、ご指摘の通り、最も多く塗れる行または列を塗ることを繰り返すという貪欲法が正解するようなテストケースしか準備されておりませんでした。そのため、以下のテストケースを追加しました。

```
4 4 3
...#
..#.
.#..
.###
```

このケースでは、先ほど説明した貪欲法を適用すると、行と列のどちらを優先したとしても「左から 1 番目の列」が最初に塗られ、残り 2 回はどちらも 2 個以下しか塗れなくなり、6 + 8 = 14 を出力します。一方、上から 1, 2, 3 番目を塗った場合、6 + 9 = 15 個塗ることができるので、貪欲法は最適解を出していないことが分かります。

2 つのテストケースを提案しただきありがとうございます。しかし、これでは「行を優先する場合」と「列を優先する場合」のうち良い方を選ぶ実装で正解することになるので、そのどちらにも対処できるケースを追加することにしました。この点、ご理解いただけますと幸いです。

square1001

**Comment by your-diary** [comment]
> *2 つのテストケースを提案しただきありがとうございます。しかし、これでは「行を優先する場合」と「列を優先する場合」のうち良い方を選ぶ実装で正解することになるので、そのどちらにも対処できるケースを追加することにしました。*

仰る通りですね……。そこの観点が完全に抜けていました。

お忙しいなか、ご対応ありがとうございます！
